import type { NewsItem } from "@/types/content";

const sourceUrl = "https://www.bulentalici.com.tr/haberler";

/** Liste sayfasında görülen kayıtlar. Yıl kaynakta yok. Kesilen cümle tamamlanmadı. */
export const news: readonly NewsItem[] = [
  {
    id: "paravizyon",
    slug: "paravizyon-roportaji",
    title: "Bülent Alıcı Paravizyon Röportajı",
    summary: "Liste sayfasında başlık ve tarih var. Gövde metin görünmedi.",
    status: "published",
    order: 1,
    listedOn: "3 Ağu",
    body: [],
    sourceName: "Paravizyon",
    sourceUrl,
  },
  {
    id: "tuketici",
    slug: "tuketici-dergisi-roportaji",
    title: "Bülent Alıcı Tüketici Dergisi Röportajı",
    summary: "Liste sayfasında başlık ve tarih var. Gövde metin görünmedi.",
    status: "published",
    order: 2,
    listedOn: "3 Ağu",
    body: [],
    sourceName: "Tüketici Dergisi",
    sourceUrl,
  },
  {
    id: "turizm-ajansi",
    slug: "turizm-ajansi",
    title: "Bülent Alıcı Turizm Ajansına Konuştu",
    summary:
      "Basit belgeli otellerin de SGK prim desteği kapsamında değerlendirilmesini istedi.",
    status: "published",
    order: 3,
    listedOn: "3 Ağu",
    body: [
      "Bülent Alıcı, sigorta prim desteği kapsamına alınmayan basit belgeli otellerin de bu destek içinde değerlendirilmesini istedi.",
      "Açıklamada, 1.900 basit belgeli otelin Kültür ve Turizm Bakanlığına bağlı çalıştığı, SGK yükümlülüklerini yerine getirdiği ve istihdam sağladığı belirtildi.",
      "Liste sayfasındaki metin yarıda kesildiği için devamı buraya yazılmadı.",
    ],
    sourceName: "Turizm Ajansı",
    sourceUrl,
  },
  {
    id: "degisim",
    slug: "ito-oteller-komitesinde-degisim",
    title: "İTO Oteller Komitesi'nde değişim rüzgarı",
    summary: "İstanbul'un turizmden aldığı pay ve seçim sürecine dair röportaj özeti.",
    status: "published",
    order: 4,
    listedOn: "3 Ağu",
    body: [
      "Yazıda İstanbul'un büyük bir turizm destinasyonu olmasına rağmen turizmden hak ettiği payı tam alamadığı belirtiliyor.",
      "Aynı yazı, İTO 16. Oteller Komitesi seçimlerinin ekim ayında yapılacağını söylüyor. Yıl, liste metninde yok.",
      "Bülent Alıcı'nın aktarılan sözleri: “İstanbul kazanacaksa değişim şart.” ve “İstanbul'un turizmde yeni vizyonunu ortaya koyacağız.”",
      "Liste sayfasındaki metin yarıda kesildiği için devamı buraya yazılmadı.",
    ],
    sourceName: "Basın derlemesi",
    sourceUrl,
  },
  {
    id: "hotel-gazetesi-agustos",
    slug: "hotel-gazetesi-prim-destegi",
    title: "Bülent Alıcı Hotel Gazetesine Konuştu",
    summary: "SGK prim desteğinin belge ayrımı yapılmadan uygulanmasını istedi.",
    status: "published",
    order: 5,
    listedOn: "3 Ağu",
    body: [
      "Bülent Alıcı, turizm sektörüne sağlanan SGK prim desteğinin yalnızca turizm işletmesi belgeli tesislerle sınırlı kalmaması gerektiğini söyledi.",
      "Hotel Gazetesi metninde İstanbul'da yaklaşık 1.900 basit konaklama belgeli tesis olduğu, bu işletmelerin vergi ödediği ve kayıtlı istihdam sağladığı yazıyor.",
      "Liste sayfasındaki metin yarıda kesildiği için devamı buraya yazılmadı.",
    ],
    sourceName: "Hotel Gazetesi",
    sourceUrl,
  },
  {
    id: "turizm-aktuel",
    slug: "turizm-aktuel-roportaji",
    title: "Bülent Alıcı Turizm Aktüel Röportajı",
    summary: "Doluluk oranından çok, şehre değer bırakan ziyaretçi hedefleniyor.",
    status: "published",
    order: 6,
    listedOn: "22 Nis",
    body: [
      "Röportajda Bülent Alıcı, Türk turizminin yalnızca doluluk oranlarını değil, üretilen değeri de konuşması gerektiğini söylüyor.",
      "Hedefi, transit yolcu sayısını artırmak değil, İstanbul'a girip şehre ekonomik değer bırakan ziyaretçi sayısını artırmak olarak anlatıyor.",
      "Turizmin otel, esnaf, restoran, ulaşım ve ticareti birlikte etkilediği belirtiliyor.",
      "Liste sayfasındaki metin yarıda kesildiği için devamı buraya yazılmadı.",
    ],
    sourceName: "Turizm Aktüel",
    sourceUrl,
  },
  {
    id: "itb",
    slug: "itb-berlin-2026",
    title: "Bülent Alıcı Turizm Aktüel'e Konuştu",
    summary: "2026 ITB Berlin kapsamında Turizm Aktüel röportajı paylaşıldı.",
    status: "published",
    order: 7,
    listedOn: "22 Nis",
    body: [
      "2026 ITB Berlin Turizm Fuarı kapsamında Turizm Aktüel Dergisi'nde yayımlanan röportajın konusu, İstanbul'un turizm vizyonu, fuar turizmi ve sektörün ortak hareket etmesidir.",
      "Liste sayfasında röportajın tam metni yok.",
    ],
    sourceName: "Turizm Aktüel",
    sourceUrl,
  },
  {
    id: "hotel-gazetesi-nisan",
    slug: "hotel-gazetesi-nisan",
    title: "Bülent Alıcı Hotel Gazetesine Konuştu",
    summary: "22 Nis tarihli ikinci Hotel Gazetesi kaydı. Liste sayfasında gövde metin görünmedi.",
    status: "published",
    order: 8,
    listedOn: "22 Nis",
    body: [],
    sourceName: "Hotel Gazetesi",
    sourceUrl,
  },
  {
    id: "klass",
    slug: "klass-magazine",
    title: "Bülent Alıcı Klass Magazine'e Konuştu",
    summary: "Liste sayfasında başlık ve tarih var. Gövde metin görünmedi.",
    status: "published",
    order: 9,
    listedOn: "22 Nis",
    body: [],
    sourceName: "Klass Magazine",
    sourceUrl,
  },
];
